[package]
name = "bff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1.1"
